# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1371, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1371, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/background1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 291, 361))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/iran man.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1180, 550, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1180, 610, 171, 41))
        self.pushButton_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 60, 551, 361))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/input 2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(590, 120, 451, 261))
        self.textBrowser.setStyleSheet("border-style: None;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 320, 171, 61))
        self.textBrowser_2.setStyleSheet("border-style: None;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(1190, 70, 131, 71))
        self.textBrowser_3.setStyleSheet("border-style: None;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1190, 220, 131, 71))
        self.textBrowser_4.setStyleSheet("border-style: None;\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(1190, 360, 131, 71))
        self.textBrowser_5.setStyleSheet("border-style: None;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(50, 70, 141, 121))
        self.textBrowser_6.setStyleSheet("border-style: None;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(30, 240, 181, 51))
        self.textBrowser_7.setStyleSheet("border-style: None;\n"
"background: transparent;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 510, 431, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/INTIATING SYSTEM.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(40, 410, 161, 31))
        self.textBrowser_8.setStyleSheet("border-style: None;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(60, 550, 121, 81))
        self.textBrowser_9.setStyleSheet("border-style: None;\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_9.setObjectName("textBrowser_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("voice assistance", "voice assistance"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
